using Volo.Abp;

namespace AggregateRootEventTriggeringBug.EntityFrameworkCore;

public abstract class AggregateRootEventTriggeringBugEntityFrameworkCoreTestBase : AggregateRootEventTriggeringBugTestBase<AggregateRootEventTriggeringBugEntityFrameworkCoreTestModule>
{

}
