using Xunit;

namespace AggregateRootEventTriggeringBug.EntityFrameworkCore;

[CollectionDefinition(AggregateRootEventTriggeringBugTestConsts.CollectionDefinitionName)]
public class AggregateRootEventTriggeringBugEntityFrameworkCoreCollection : ICollectionFixture<AggregateRootEventTriggeringBugEntityFrameworkCoreFixture>
{

}
