using AggregateRootEventTriggeringBug.EntityFrameworkCore;
using Xunit;

namespace AggregateRootEventTriggeringBug.EntityFrameworkCore;

public class AggregateRootEventTriggeringBugEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<AggregateRootEventTriggeringBugEntityFrameworkCoreFixture>
{

}
